server:
  port: 8090

spring:
  application:
    name: Cliente-e-commerce

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3307/cliente_db?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:alexx}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true