services:
  cliente_mysql:
    image: mysql:9.4.0
    container_name: cliente_MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${CLIENTE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CLIENTE_DATABASE}
      MYSQL_USER: ${CLIENTE_USERNAME}
      MYSQL_PASSWORD: ${CLIENTE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - cliente-db:/var/lib/mysql

  produto_mysql:
    image: mysql:9.4.0
    container_name: produto_MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUTO_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PRODUTO_DATABASE}
      MYSQL_USER: ${PRODUTO_USERNAME}
      MYSQL_PASSWORD: ${PRODUTO_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - produto-db:/var/lib/mysql

  pedido_mysql:
    image: mysql:9.4.0
    container_name: pedido_MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${PEDIDO_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PEDIDO_DATABASE}
      MYSQL_USER: ${PEDIDO_USERNAME}
      MYSQL_PASSWORD: ${PEDIDO_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - pedido-db:/var/lib/mysql

volumes:
  cliente-db:
  produto-db:
  pedido-db: